import { useEffect, useState } from 'react';
import { onAuthStateChanged, signInWithEmailAndPassword, signOut, type User } from 'firebase/auth';
import { collection, doc, getDoc, onSnapshot, type QuerySnapshot, type DocumentData } from 'firebase/firestore';
import { deleteObject, getDownloadURL, listAll, ref, uploadBytes } from 'firebase/storage';
import { Activity, AlertTriangle, BarChart3, Check, ChevronLeft, ChevronRight, FileImage, FolderOpen, LayoutDashboard, LogOut, Menu, Search, Shield, Users, X } from 'lucide-react';
import { auth, db, storage } from './firebase';
import { count, readPage, updateRecord, updateUser } from './services';
import { AnnouncementsManagement, AttendanceManagement, ClassesManagement, ReportsManagement, StudentsManagement, UsersManagement } from './management';
import type { AdminPage, RecordData, UserProfile } from './types';

const pages: { id: AdminPage; label: string; icon: typeof LayoutDashboard }[] = [
  { id: 'dashboard', label: 'Overview', icon: LayoutDashboard }, { id: 'users', label: 'Users', icon: Users },
  { id: 'children', label: 'Children', icon: Shield }, { id: 'classes', label: 'Classes', icon: Users }, { id: 'pickups', label: 'Pickups', icon: Activity },
  { id: 'attendance', label: 'Attendance', icon: Check }, { id: 'announcements', label: 'Announcements', icon: Activity }, { id: 'reports', label: 'Reports', icon: AlertTriangle }, { id: 'files', label: 'Files', icon: FolderOpen }
];
const roles = ['admin', 'teacher', 'parent', 'security', 'pickup_verifier'];
const friendlyError = (error: unknown) => error instanceof Error ? error.message.replace('Firebase: ', '').replace(/ \(.+\)$/, '') : 'Something went wrong. Please try again.';
const formatDate = (value: unknown) => {
  if (!value) return 'No date';
  const date = typeof value === 'object' && value && 'toDate' in value ? (value as { toDate: () => Date }).toDate() : new Date(String(value));
  return Number.isNaN(date.getTime()) ? 'No date' : date.toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });
};

export function AdminApp() {
  const [firebaseUser, setFirebaseUser] = useState<User | null>(null);
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [authLoading, setAuthLoading] = useState(true);
  useEffect(() => onAuthStateChanged(auth, async (user) => {
    setFirebaseUser(user); setProfile(null);
    if (user) { try { const snapshot = await getDoc(doc(db, 'users', user.uid)); if (snapshot.exists()) setProfile({ id: snapshot.id, uid: user.uid, ...snapshot.data() } as UserProfile); } catch { setProfile(null); } }
    setAuthLoading(false);
  }), []);
  if (authLoading) return <div className="center-page"><div className="loader" /></div>;
  if (!firebaseUser) return <Login />;
  if (profile?.role !== 'admin') return <Denied email={firebaseUser.email || ''} />;
  return <AdminWorkspace profile={profile} />;
}

function Login() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await signInWithEmailAndPassword(auth, email.trim(), password); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } };
  return <main className="login-page"><section className="login-art"><div className="brand-mark">SC</div><p className="eyebrow">SAFE CHILD / ADMINISTRATION</p><h1>Clarity when campus safety matters.</h1><p>Monitor people, pickup operations, and incidents from one trusted workspace.</p></section><form className="login-card" onSubmit={submit}><div className="brand-line"><span className="brand-mark small">SC</span><span>Safe Child</span></div><h2>Administrator sign in</h2><p className="muted">Use an administrator account from the existing Firebase project.</p>{error && <Notice kind="error">{error}</Notice>}<label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="email" /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required autoComplete="current-password" /></label><button className="primary full" disabled={busy}>{busy ? 'Signing in...' : 'Sign in'} <ChevronRight size={17} /></button><p className="login-foot">Access is enforced by Firebase Authentication and Firestore rules.</p></form></main>;
}

function Denied({ email }: { email: string }) { return <div className="center-page"><div className="denied"><Shield size={42} /><h2>Administrator access required</h2><p>{email} is authenticated but does not have the <b>admin</b> role.</p><button className="secondary" onClick={() => signOut(auth)}><LogOut size={16} /> Sign out</button></div></div>; }

function AdminWorkspace({ profile }: { profile: UserProfile }) {
  const [page, setPage] = useState<AdminPage>((location.pathname.split('/')[2] as AdminPage) || 'dashboard');
  const [mobileNav, setMobileNav] = useState(false);
  const navigate = (next: AdminPage) => { history.pushState({}, '', next === 'dashboard' ? '/admin' : `/admin/${next}`); setPage(next); setMobileNav(false); };
  useEffect(() => { const onPop = () => setPage((location.pathname.split('/')[2] as AdminPage) || 'dashboard'); addEventListener('popstate', onPop); return () => removeEventListener('popstate', onPop); }, []);
  return <div className="app-shell"><aside className={mobileNav ? 'sidebar open' : 'sidebar'}><div className="brand-line sidebar-brand"><span className="brand-mark small">SC</span><span>Safe Child</span><button className="icon-button close-nav" onClick={() => setMobileNav(false)}><X size={19} /></button></div><p className="nav-caption">Workspace</p><nav>{pages.map(({ id, label, icon: Icon }) => <button className={page === id ? 'nav-item active' : 'nav-item'} key={id} onClick={() => navigate(id)}><Icon size={18} />{label}</button>)}</nav><div className="sidebar-foot"><div className="avatar">{(profile.displayName || profile.email || 'A')[0].toUpperCase()}</div><div className="profile-mini"><b>{profile.displayName || 'Administrator'}</b><span>{profile.email}</span></div><button className="icon-button" title="Sign out" onClick={() => signOut(auth)}><LogOut size={17} /></button></div></aside>{mobileNav && <button className="scrim" onClick={() => setMobileNav(false)} aria-label="Close navigation" />}<main className="main"><header className="topbar"><button className="icon-button menu-button" onClick={() => setMobileNav(true)}><Menu size={21} /></button><div><p className="eyebrow">ADMIN CONSOLE</p><h1>{pages.find((item) => item.id === page)?.label}</h1></div><div className="topbar-right"><span className="top-user">{profile.displayName || profile.email}</span></div></header>{page === 'dashboard' && <Home navigate={navigate} />}{page === 'users' && <UsersManagement />}{page === 'children' && <StudentsManagement />}{page === 'classes' && <ClassesManagement />}{page === 'pickups' && <CollectionPage name="pickup_requests" title="Pickup requests" subtitle="Pickup authorization and gate activity" columns={['studentName', 'pickupName', 'status', 'createdAt']} editable="pickup" />}{page === 'attendance' && <AttendanceManagement />}{page === 'announcements' && <AnnouncementsManagement />}{page === 'reports' && <ReportsManagement />}{page === 'files' && <Files />}</main></div>;
}

function Dashboard({ profile }: { profile: UserProfile }) {
  const [page, setPage] = useState<AdminPage>((location.pathname.split('/')[2] as AdminPage) || 'dashboard'); const [mobileNav, setMobileNav] = useState(false);
  const navigate = (next: AdminPage) => { history.pushState({}, '', next === 'dashboard' ? '/admin' : `/admin/${next}`); setPage(next); setMobileNav(false); };
  useEffect(() => { const onPop = () => setPage((location.pathname.split('/')[2] as AdminPage) || 'dashboard'); addEventListener('popstate', onPop); return () => removeEventListener('popstate', onPop); }, []);
  return <div className="app-shell"><aside className={mobileNav ? 'sidebar open' : 'sidebar'}><div className="brand-line sidebar-brand"><span className="brand-mark small">SC</span><span>Safe Child</span><button className="icon-button close-nav" onClick={() => setMobileNav(false)}><X size={19} /></button></div><p className="nav-caption">Workspace</p><nav>{pages.map(({ id, label, icon: Icon }) => <button className={page === id ? 'nav-item active' : 'nav-item'} key={id} onClick={() => navigate(id)}><Icon size={18} />{label}</button>)}</nav><div className="sidebar-foot"><div className="avatar">{(profile.displayName || profile.email || 'A')[0].toUpperCase()}</div><div className="profile-mini"><b>{profile.displayName || 'Administrator'}</b><span>{profile.email}</span></div><button className="icon-button" title="Sign out" onClick={() => signOut(auth)}><LogOut size={17} /></button></div></aside>{mobileNav && <button className="scrim" onClick={() => setMobileNav(false)} aria-label="Close navigation" /> }<main className="main"><header className="topbar"><button className="icon-button menu-button" onClick={() => setMobileNav(true)}><Menu size={21} /></button><div><p className="eyebrow">ADMIN CONSOLE</p><h1>{pages.find((item) => item.id === page)?.label}</h1></div><div className="topbar-right"><span className="top-user">{profile.displayName || profile.email}</span></div></header>{page === 'dashboard' && <Home navigate={navigate} />}{page === 'users' && <CollectionPage name="users" title="Users" subtitle="Accounts and role access across Safe Child" columns={['displayName', 'email', 'role', 'status', 'createdAt']} editable="user" />}{page === 'children' && <CollectionPage name="students" title="Children" subtitle="Student records and guardian relationships" columns={['firstName', 'lastName', 'grade', 'guardianName', 'status']} editable="student" />}{page === 'pickups' && <CollectionPage name="pickup_requests" title="Pickup requests" subtitle="Review authorization and handover progress" columns={['studentName', 'pickupName', 'status', 'pickupPhone', 'createdAt']} editable="pickup" />}{page === 'reports' && <CollectionPage name="reports" title="Reports" subtitle="Incident and safety reports, when present in Firestore" columns={['title', 'reportType', 'status', 'createdByUserId', 'createdAt']} editable="report" />}{page === 'files' && <Files />}</main></div>;
}

function Home({ navigate }: { navigate: (page: AdminPage) => void }) {
  const [stats, setStats] = useState<Record<string, number>>({}); const [recent, setRecent] = useState<RecordData[]>([]); const [announcements, setAnnouncements] = useState<RecordData[]>([]); const [error, setError] = useState('');
  useEffect(() => { Promise.allSettled(['users', 'students', 'pickup_requests', 'alerts'].map(async (name) => [name, await count(name)] as const)).then((results) => { const available = results.filter((result): result is PromiseFulfilledResult<readonly [string, number]> => result.status === 'fulfilled'); setStats(Object.fromEntries(available.map((result) => result.value))); if (available.length < results.length) setError('Some optional collections could not be read.'); }).catch((e) => setError(friendlyError(e))); const unsubscribeUsers = onSnapshot(collection(db, 'users'), (snapshot: QuerySnapshot<DocumentData>) => setRecent(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as RecordData)).sort((a: RecordData, b: RecordData) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))).slice(0, 5)), (e) => setError(friendlyError(e))); const unsubscribeAnnouncements = onSnapshot(collection(db, 'announcements'), (snapshot) => setAnnouncements(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as RecordData)).sort((a, b) => String(b.createdAt || b.date || '').localeCompare(String(a.createdAt || a.date || ''))).slice(0, 5)), (e) => setError(friendlyError(e))); return () => { unsubscribeUsers(); unsubscribeAnnouncements(); }; }, []);
  const cards = [{ key: 'users', label: 'Total users', icon: Users, tone: 'blue' }, { key: 'students', label: 'Children records', icon: Shield, tone: 'green' }, { key: 'pickup_requests', label: 'Pickup requests', icon: Activity, tone: 'amber' }, { key: 'alerts', label: 'Security alerts', icon: AlertTriangle, tone: 'red' }];
  return <div className="content"><div className="welcome"><div><p className="eyebrow">OPERATIONS SNAPSHOT</p><h2>Good morning, Admin.</h2><p className="muted">A live view of the records your team is responsible for.</p></div><button className="secondary" onClick={() => navigate('users')}><Users size={17} /> Manage users</button></div>{error && <Notice kind="error">Some data could not be loaded: {error}</Notice>}<div className="stat-grid">{cards.map(({ key, label, icon: Icon, tone }) => <div className="stat-card" key={key}><div className={`stat-icon ${tone}`}><Icon size={19} /></div><div><span>{label}</span><strong>{stats[key] ?? '...'}</strong></div></div>)}</div><section className="panel"><div className="panel-heading"><div><h3>Recent registrations</h3><p className="muted">Latest profiles in the shared users collection</p></div><button className="text-button" onClick={() => navigate('users')}>View all <ChevronRight size={16} /></button></div>{recent.length ? <div className="activity-list">{recent.map((user) => <div className="activity" key={user.id}><div className="avatar soft">{String(user.displayName || user.email || 'U')[0].toUpperCase()}</div><div><b>{String(user.displayName || 'Unnamed user')}</b><span>{String(user.email || 'No email')} · {String(user.role || 'No role')}</span></div><time>{formatDate(user.createdAt)}</time></div>)}</div> : <Empty text="No registrations available yet." />}</section><section className="panel dashboard-announcements"><div className="panel-heading"><div><h3>Announcements</h3><p className="muted">Latest bulletins published to the Safe Child app</p></div></div>{announcements.length ? <div className="activity-list">{announcements.map((announcement) => <div className="activity" key={announcement.id}><div className="avatar soft">!</div><div><b>{String(announcement.title || 'Untitled announcement')}</b><span>{String(announcement.body || 'No announcement details')}</span></div><time>{formatDate(announcement.createdAt || announcement.date)}</time></div>)}</div> : <Empty text="No announcements available yet." />}</section></div>;
}

function CollectionPage({ name, title, subtitle, columns, editable }: { name: string; title: string; subtitle: string; columns: string[]; editable: string }) {
  const [records, setRecords] = useState<RecordData[]>([]); const [cursor, setCursor] = useState<NonNullable<Awaited<ReturnType<typeof readPage>>['cursor']>>(); const [history, setHistory] = useState<typeof cursor[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState<RecordData | null>(null);
  const load = async (nextCursor?: typeof cursor) => { setLoading(true); setError(''); try { const result = await readPage(name, 12, nextCursor, search); setRecords(result.records); setCursor(result.cursor); } catch (e) { setError(friendlyError(e)); setRecords([]); } finally { setLoading(false); } };
  useEffect(() => { setHistory([]); load(); }, [name]);
  if (name === 'reports') return <ReportsManagement />;
  const label = (column: string) => column.replace(/([A-Z])/g, ' $1').replace(/^./, (value) => value.toUpperCase());
  return <div className="content"><div className="page-heading"><div><p className="eyebrow">DATA MANAGEMENT</p><h2>{title}</h2><p className="muted">{subtitle}</p></div><div className="toolbar"><div className="search"><Search size={17} /><input placeholder={`Search ${title.toLowerCase()}...`} value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && load()} /></div><button className="secondary search-submit" onClick={() => load()}><Search size={16} /> Search</button></div></div>{error && <Notice kind="error">{error}</Notice>}<section className="panel table-panel">{loading ? <div className="loading-row"><div className="loader" />Loading records...</div> : records.length ? <div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column}>{label(column)}</th>)}<th>Actions</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}>{columns.map((column) => <td key={column}>{column === 'createdAt' || column.endsWith('At') ? formatDate(record[column]) : <Value value={record[column]} />}</td>)}<td><button className="table-action" onClick={() => setSelected(record)}>View / edit</button></td></tr>)}</tbody></table></div> : <Empty text={name === 'reports' && !error ? 'No reports collection records found.' : 'No records match this search.'} />}<div className="pagination"><span>{records.length ? `Showing ${records.length} records` : 'No records'}</span><div><button className="icon-button" disabled={!history.length || loading} onClick={() => { const previous = [...history]; const cursorBack = previous.pop(); setHistory(previous); load(cursorBack); }}><ChevronLeft size={17} /></button><button className="icon-button" disabled={!cursor || loading} onClick={() => { setHistory([...history, cursor]); load(cursor); }}><ChevronRight size={17} /></button></div></div></section>{selected && <EditModal record={selected} kind={editable} onClose={() => setSelected(null)} onSaved={() => { setSelected(null); load(); }} />}</div>;
}

function Value({ value }: { value: unknown }) { const text = String(value ?? '—'); return <span className={['active', 'Active', 'open', 'Open'].includes(text) ? 'badge green' : ['admin', 'High'].includes(text) ? 'badge red' : ['Pending', 'teacher'].includes(text) ? 'badge amber' : ''}>{text.replace(/_/g, ' ')}</span>; }
function EditModal({ record, kind, onClose, onSaved }: { record: RecordData; kind: string; onClose: () => void; onSaved: () => void }) { const [status, setStatus] = useState(String(record.status || '')); const [role, setRole] = useState(String(record.role || 'parent')); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const save = async () => { setBusy(true); try { if (kind === 'user') await updateUser(record.id, { role, status }); else if (kind === 'report') await updateRecord('reports', record.id, { status }); else await updateRecord(kind === 'student' ? 'students' : 'pickup_requests', record.id, { status }); onSaved(); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }; return <div className="modal-layer" role="dialog"><div className="modal"><div className="modal-heading"><div><p className="eyebrow">RECORD DETAIL</p><h3>{String(record.displayName || `${record.firstName || ''} ${record.lastName || ''}` || record.title || 'Record')}</h3></div><button className="icon-button" onClick={onClose}><X size={19} /></button></div>{error && <Notice kind="error">{error}</Notice>}<div className="detail-grid">{Object.entries(record).filter(([key]) => key !== 'id' && typeof record[key] !== 'object').slice(0, 12).map(([key, value]) => <div key={key}><span>{key.replace(/([A-Z])/g, ' $1')}</span><b>{String(value ?? '—')}</b></div>)}</div>{kind === 'user' && <label>Role<select value={role} onChange={(e) => setRole(e.target.value)}>{roles.map((item) => <option key={item}>{item}</option>)}</select></label>}<label>Status<input value={status} onChange={(e) => setStatus(e.target.value)} /></label><div className="modal-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={save} disabled={busy}>{busy ? 'Saving...' : 'Save changes'} <Check size={16} /></button></div></div></div>; }

function Files() { const [files, setFiles] = useState<{ name: string; url?: string; path: string }[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const load = async () => { try { const result = await listAll(ref(storage)); setFiles(await Promise.all(result.items.map(async (item) => ({ name: item.name, path: item.fullPath, url: await getDownloadURL(item) })))); } catch (e) { setError(friendlyError(e)); } }; useEffect(() => { load(); }, []); const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setBusy(true); try { await uploadBytes(ref(storage, `admin/${Date.now()}-${file.name}`), file); await load(); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); event.target.value = ''; } }; const remove = async (path: string) => { if (!confirm('Delete this Firebase Storage file? This cannot be undone.')) return; try { await deleteObject(ref(storage, path)); await load(); } catch (e) { setError(friendlyError(e)); } }; return <div className="content"><div className="page-heading"><div><p className="eyebrow">FIREBASE STORAGE</p><h2>Files</h2><p className="muted">Existing Storage objects available to this administrator.</p></div><label className="primary upload"><FileImage size={17} />{busy ? 'Uploading...' : 'Upload file'}<input type="file" accept="image/*,.pdf" onChange={upload} disabled={busy} /></label></div>{error && <Notice kind="error">Storage could not be loaded: {error}</Notice>}<section className="panel file-grid">{files.length ? files.map((file) => <article className="file-card" key={file.path}>{file.url && file.name.match(/\.(png|jpe?g|gif|webp)$/i) ? <img src={file.url} alt={file.name} /> : <div className="file-placeholder"><FileImage size={28} /></div>}<div><b title={file.name}>{file.name}</b><button className="danger-button" onClick={() => remove(file.path)}>Delete</button></div></article>) : <Empty text={error ? 'Storage listing unavailable.' : 'No Firebase Storage files found.'} />}</section></div>; }
function Notice({ children, kind }: { children: React.ReactNode; kind: 'error' | 'success' }) { return <div className={`notice ${kind}`}>{kind === 'error' ? <AlertTriangle size={16} /> : <Check size={16} />}{children}</div>; }
function Empty({ text }: { text: string }) { return <div className="empty"><BarChart3 size={25} /><p>{text}</p></div>; }