import { useEffect, useMemo, useState } from 'react';
import { addDoc, collection, onSnapshot, query, orderBy, type DocumentData } from 'firebase/firestore';
import { Check, Edit3, Plus, Trash2, Upload, X } from 'lucide-react';
import { db } from './firebase';
import { createRecord, deleteRecord, deleteUser, updateRecord, updateUser } from './services';
import type { RecordData, Role } from './types';

const roles: Role[] = ['admin', 'teacher', 'parent', 'security', 'pickup_verifier'];
const fieldLabel = (value: string) => value.replace(/([A-Z])/g, ' $1').replace(/^./, (letter) => letter.toUpperCase());
const csvRow = (line: string) => {
  const values: string[] = []; let value = ''; let quoted = false;
  for (let index = 0; index < line.length; index += 1) {
    const character = line[index];
    if (character === '"' && line[index + 1] === '"') { value += '"'; index += 1; }
    else if (character === '"') quoted = !quoted;
    else if (character === ',' && !quoted) { values.push(value.trim()); value = ''; }
    else value += character;
  }
  values.push(value.trim()); return values;
};
const csvValue = (headers: string[], values: string[], ...names: string[]) => {
  const position = names.map((name) => headers.indexOf(name)).find((index) => index >= 0);
  return position === undefined ? '' : values[position] || '';
};

function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  return <div className="modal-layer" role="dialog"><div className="modal"><div className="modal-heading"><div><p className="eyebrow">DATA MANAGEMENT</p><h3>{title}</h3></div><button className="icon-button" onClick={onClose}><X size={19} /></button></div>{children}</div></div>;
}
function Actions({ onEdit, onDelete }: { onEdit: () => void; onDelete: () => void }) { return <div className="row-actions"><button className="table-action" onClick={onEdit}><Edit3 size={14} /> Edit</button><button className="danger-button" onClick={onDelete}><Trash2 size={14} /> Delete</button></div>; }
function Field({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label>{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function SaveBar({ busy, onCancel, onSave }: { busy: boolean; onCancel: () => void; onSave: () => void }) { return <div className="modal-actions"><button className="secondary" onClick={onCancel}>Cancel</button><button className="primary" onClick={onSave} disabled={busy}>{busy ? 'Saving...' : 'Save changes'} <Check size={16} /></button></div>; }

export function UsersManagement() {
  const [users, setUsers] = useState<RecordData[]>([]); const [selected, setSelected] = useState<RecordData | null>(null); const [error, setError] = useState('');
  useEffect(() => onSnapshot(query(collection(db, 'users'), orderBy('displayName')), (snapshot) => setUsers(snapshot.docs.map((item) => ({ id: item.id, ...item.data() }))), (e) => setError(e.message)), []);
  const remove = async (user: RecordData) => { if (!confirm(`Delete ${String(user.displayName || user.email || 'this user')}? This removes the profile record; the authentication account requires server-side deletion.`)) return; try { await deleteUser(user.id); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete user.'); } };
  return <ManagementLayout title="Users" subtitle="Edit account details, roles, and profile records.">{error && <div className="notice error">{error}</div>}<section className="panel table-panel"><Table headers={['displayName', 'email', 'role', 'status']} rows={users} renderActions={(row) => <Actions onEdit={() => setSelected(row)} onDelete={() => remove(row)} />} />{selected && <UserModal record={selected} onClose={() => setSelected(null)} />}</section></ManagementLayout>;
}
function UserModal({ record, onClose }: { record: RecordData; onClose: () => void }) {
  const [form, setForm] = useState({ displayName: String(record.displayName || ''), email: String(record.email || ''), phone: String(record.phone || ''), role: String(record.role || 'parent'), status: String(record.status || 'Active') }); const [busy, setBusy] = useState(false); const set = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { setBusy(true); try { await updateUser(record.id, form); onClose(); } catch { setBusy(false); } };
  return <Modal title="Edit user account" onClose={onClose}><Field label="Display name" value={form.displayName} onChange={(value) => set('displayName', value)} /><Field label="Email" value={form.email} onChange={(value) => set('email', value)} type="email" /><Field label="Phone" value={form.phone} onChange={(value) => set('phone', value)} /><label>Role<select value={form.role} onChange={(event) => set('role', event.target.value)}>{roles.map((role) => <option key={role}>{role}</option>)}</select></label><Field label="Status" value={form.status} onChange={(value) => set('status', value)} /><SaveBar busy={busy} onCancel={onClose} onSave={save} /></Modal>;
}

export function StudentsManagement() {
  const [students, setStudents] = useState<RecordData[]>([]); const [users, setUsers] = useState<RecordData[]>([]); const [classes, setClasses] = useState<RecordData[]>([]); const [selected, setSelected] = useState<RecordData | null>(null); const [addOpen, setAddOpen] = useState(false); const [importing, setImporting] = useState(false); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  useEffect(() => onSnapshot(collection(db, 'students'), (snapshot) => setStudents(snapshot.docs.map((item) => ({ id: item.id, ...item.data() }))), (e) => setError(e.message)), []);
  useEffect(() => onSnapshot(collection(db, 'users'), (snapshot) => setUsers(snapshot.docs.map((item) => ({ id: item.id, ...item.data() })))), []);
  useEffect(() => onSnapshot(collection(db, 'classes'), (snapshot) => setClasses(snapshot.docs.map((item) => ({ id: item.id, ...item.data() })))), []);
  const parents = users.filter((user) => user.role === 'parent'); const teachers = users.filter((user) => user.role === 'teacher');
  const visible = useMemo(() => students.filter((student) => JSON.stringify(student).toLowerCase().includes(search.toLowerCase())), [students, search]);
  const remove = async (student: RecordData) => { if (!confirm(`Delete ${String(student.firstName || '')} ${String(student.lastName || '')}?`)) return; try { await deleteRecord('students', student.id); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete student.'); } };
  const importCsv = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setImporting(true); const reader = new FileReader(); reader.onload = async () => { try { const lines = String(reader.result || '').split(/\r?\n/).filter(Boolean); if (lines.length < 2) throw new Error('CSV needs a header and at least one row.'); const headers = csvRow(lines[0]).map((header) => header.toLowerCase().replace(/[^a-z0-9]/g, '')); for (const line of lines.slice(1)) { const values = csvRow(line); const firstName = csvValue(headers, values, 'firstname', 'studentfirstname', 'name'); if (!firstName) continue; await createRecord('students', { firstName, lastName: csvValue(headers, values, 'lastname', 'studentlastname') || 'Imported', grade: csvValue(headers, values, 'grade', 'gradelevel') || 'Unassigned', guardianName: csvValue(headers, values, 'guardianname', 'parentname'), guardianEmail: csvValue(headers, values, 'guardianemail', 'parentemail').toLowerCase(), guardianPhone: csvValue(headers, values, 'guardianphone', 'parentphone'), emergencyContact: csvValue(headers, values, 'emergencycontact'), teacherName: csvValue(headers, values, 'teachername'), teacherEmail: csvValue(headers, values, 'teacheremail').toLowerCase(), status: 'Active' }); } } catch (e) { setError(e instanceof Error ? e.message : 'CSV import failed.'); } finally { setImporting(false); event.target.value = ''; } }; reader.readAsText(file); };
  return <ManagementLayout title="Students" subtitle="Add, import, edit, assign, and remove student records."><div className="management-actions"><div className="search"><input placeholder="Search students..." value={search} onChange={(event) => setSearch(event.target.value)} /></div><button className="secondary" onClick={() => setAddOpen(true)}><Plus size={16} /> Add student</button><label className="primary upload"><Upload size={16} />{importing ? 'Importing...' : 'Import CSV'}<input type="file" accept=".csv,text/csv" onChange={importCsv} disabled={importing} /></label></div>{error && <div className="notice error">{error}</div>}<section className="panel table-panel"><Table headers={['firstName', 'lastName', 'grade', 'guardianName', 'className']} rows={visible} renderActions={(row) => <Actions onEdit={() => setSelected(row)} onDelete={() => remove(row)} />} />{selected && <StudentModal record={selected} parents={parents} teachers={teachers} classes={classes} onClose={() => setSelected(null)} />}{addOpen && <StudentModal parents={parents} teachers={teachers} classes={classes} onClose={() => setAddOpen(false)} />}</section></ManagementLayout>;
}
function StudentModal({ record, parents, teachers, classes, onClose }: { record?: RecordData; parents: RecordData[]; teachers: RecordData[]; classes: RecordData[]; onClose: () => void }) {
  const [form, setForm] = useState({ firstName: String(record?.firstName || ''), lastName: String(record?.lastName || ''), grade: String(record?.grade || ''), guardianName: String(record?.guardianName || ''), guardianEmail: String(record?.guardianEmail || ''), guardianPhone: String(record?.guardianPhone || ''), teacherName: String(record?.teacherName || ''), teacherEmail: String(record?.teacherEmail || ''), classId: String(record?.classId || ''), className: String(record?.className || '') }); const [busy, setBusy] = useState(false); const set = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { setBusy(true); try { const parent = parents.find((user) => user.email === form.guardianEmail); const teacher = teachers.find((user) => user.email === form.teacherEmail); const fields = { ...form, guardianName: parent?.displayName || form.guardianName, teacherName: teacher?.displayName || form.teacherName, status: 'Active' }; if (record) await updateRecord('students', record.id, fields); else await createRecord('students', fields); onClose(); } catch { setBusy(false); } };
  return <Modal title={record ? 'Edit student and assignments' : 'Add student'} onClose={onClose}><Field label="First name" value={form.firstName} onChange={(value) => set('firstName', value)} /><Field label="Last name" value={form.lastName} onChange={(value) => set('lastName', value)} /><Field label="Grade" value={form.grade} onChange={(value) => set('grade', value)} /><label>Parent account<select value={form.guardianEmail} onChange={(event) => set('guardianEmail', event.target.value)}><option value="">Select parent</option>{parents.map((parent) => <option key={parent.id} value={String(parent.email || '')}>{String(parent.displayName || parent.email)}</option>)}</select></label><Field label="Guardian name" value={form.guardianName} onChange={(value) => set('guardianName', value)} /><Field label="Guardian phone" value={form.guardianPhone} onChange={(value) => set('guardianPhone', value)} /><label>Teacher<select value={form.teacherEmail} onChange={(event) => set('teacherEmail', event.target.value)}><option value="">Select teacher</option>{teachers.map((teacher) => <option key={teacher.id} value={String(teacher.email || '')}>{String(teacher.displayName || teacher.email)}</option>)}</select></label><label>Grade class<select value={form.classId} onChange={(event) => { const selectedClass = classes.find((item) => item.id === event.target.value); setForm({ ...form, classId: event.target.value, className: String(selectedClass?.name || '') }); }}><option value="">Select class</option>{classes.map((item) => <option key={item.id} value={item.id}>{String(item.name || item.grade || item.id)}{item.teacherName ? ` · ${String(item.teacherName)}` : ''}</option>)}</select></label><SaveBar busy={busy} onCancel={onClose} onSave={save} /></Modal>;
}

export function ClassesManagement() {
  const [classes, setClasses] = useState<RecordData[]>([]); const [teachers, setTeachers] = useState<RecordData[]>([]); const [open, setOpen] = useState(false); const [selected, setSelected] = useState<RecordData | null>(null);
  useEffect(() => onSnapshot(collection(db, 'classes'), (snapshot) => setClasses(snapshot.docs.map((item) => ({ id: item.id, ...item.data() })))), []);
  useEffect(() => onSnapshot(collection(db, 'users'), (snapshot) => setTeachers(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as RecordData)).filter((user) => user.role === 'teacher'))), []);
  return <ManagementLayout title="Grade Classes" subtitle="Create classes and assign teachers to manage their student groups."><div className="management-actions"><button className="primary" onClick={() => { setSelected(null); setOpen(true); }}><Plus size={16} /> Create grade class</button></div><section className="panel table-panel"><Table headers={['name', 'grade', 'teacherName', 'teacherEmail']} rows={classes} renderActions={(row) => <Actions onEdit={() => { setSelected(row); setOpen(true); }} onDelete={async () => { if (confirm(`Delete ${String(row.name || 'this class')}?`)) await deleteRecord('classes', row.id); }} />} />{open && <ClassModal record={selected || undefined} teachers={teachers} onClose={() => setOpen(false)} />}</section></ManagementLayout>;
}
function ClassModal({ record, teachers, onClose }: { record?: RecordData; teachers: RecordData[]; onClose: () => void }) { const [form, setForm] = useState({ name: String(record?.name || ''), grade: String(record?.grade || ''), teacherEmail: String(record?.teacherEmail || ''), teacherName: String(record?.teacherName || '') }); const [busy, setBusy] = useState(false); const save = async () => { setBusy(true); try { const teacher = teachers.find((item) => item.email === form.teacherEmail); const fields = { ...form, teacherName: teacher?.displayName || form.teacherName }; if (record) await updateRecord('classes', record.id, fields); else await createRecord('classes', fields); onClose(); } catch { setBusy(false); } }; return <Modal title={record ? 'Edit grade class' : 'Create grade class'} onClose={onClose}><Field label="Class name" value={form.name} onChange={(value) => setForm({ ...form, name: value })} /><Field label="Grade" value={form.grade} onChange={(value) => setForm({ ...form, grade: value })} /><label>Teacher<select value={form.teacherEmail} onChange={(event) => setForm({ ...form, teacherEmail: event.target.value })}><option value="">Select teacher</option>{teachers.map((teacher) => <option key={teacher.id} value={String(teacher.email || '')}>{String(teacher.displayName || teacher.email)}</option>)}</select></label><SaveBar busy={busy} onCancel={onClose} onSave={save} /></Modal>; }

function ManagementLayout({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="content"><div className="page-heading"><div><p className="eyebrow">ADMIN MANAGEMENT</p><h2>{title}</h2><p className="muted">{subtitle}</p></div></div>{children}</div>; }
function Table({ headers, rows, renderActions }: { headers: string[]; rows: RecordData[]; renderActions: (row: RecordData) => React.ReactNode }) { return rows.length ? <div className="table-wrap"><table><thead><tr>{headers.map((header) => <th key={header}>{fieldLabel(header)}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}>{headers.map((header) => <td key={header}>{String(row[header] ?? '—')}</td>)}<td>{renderActions(row)}</td></tr>)}</tbody></table></div> : <div className="empty"><p>No records found.</p></div>; }
